# Generated by Django 5.0.3 on 2024-04-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_bitacor_alter_record_lectura'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientesTb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('contacto', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=60)),
                ('cuidad', models.CharField(max_length=50)),
                ('rfc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('nserie', models.CharField(max_length=35)),
                ('lectura', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=120)),
            ],
        ),
    ]
